"""add_sprint3_ai_models

Revision ID: 5208ed03aeb1
Revises: a79000e54375
Create Date: 2026-03-11 19:30:03.286134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5208ed03aeb1'
down_revision: Union[str, None] = 'a79000e54375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcarddeck',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcarddeck_document_version_id'), 'flashcarddeck', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_flashcarddeck_share_token'), 'flashcarddeck', ['share_token'], unique=True)
    op.create_index(op.f('ix_flashcarddeck_student_id'), 'flashcarddeck', ['student_id'], unique=False)
    op.create_table('mindmap',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('nodes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindmap_document_version_id'), 'mindmap', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_mindmap_student_id'), 'mindmap', ['student_id'], unique=False)
    op.create_table('quizsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizsession_document_version_id'), 'quizsession', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_quizsession_student_id'), 'quizsession', ['student_id'], unique=False)
    op.create_table('ragsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documentversion.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragsession_document_version_id'), 'ragsession', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_ragsession_student_id'), 'ragsession', ['student_id'], unique=False)
    op.create_table('flashcard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcarddeck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_deck_id'), 'flashcard', ['deck_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('cosine_similarity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ragsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_session_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_session_id'], ['quizsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_quiz_session_id'), 'question', ['quiz_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_quiz_session_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_flashcard_deck_id'), table_name='flashcard')
    op.drop_table('flashcard')
    op.drop_index(op.f('ix_ragsession_student_id'), table_name='ragsession')
    op.drop_index(op.f('ix_ragsession_document_version_id'), table_name='ragsession')
    op.drop_table('ragsession')
    op.drop_index(op.f('ix_quizsession_student_id'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_document_version_id'), table_name='quizsession')
    op.drop_table('quizsession')
    op.drop_index(op.f('ix_mindmap_student_id'), table_name='mindmap')
    op.drop_index(op.f('ix_mindmap_document_version_id'), table_name='mindmap')
    op.drop_table('mindmap')
    op.drop_index(op.f('ix_flashcarddeck_student_id'), table_name='flashcarddeck')
    op.drop_index(op.f('ix_flashcarddeck_share_token'), table_name='flashcarddeck')
    op.drop_index(op.f('ix_flashcarddeck_document_version_id'), table_name='flashcarddeck')
    op.drop_table('flashcarddeck')
    # ### end Alembic commands ###