"""add_created_at_to_contribution

Revision ID: 96029914f94b
Revises: 99ecea9fcb0d
Create Date: 2026-03-15 21:39:37.652324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = '96029914f94b'
down_revision: Union[str, None] = '99ecea9fcb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contribution', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_contribution_created_at'), 'contribution', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_created_at'), table_name='contribution')
    op.drop_column('contribution', 'created_at')
    # ### end Alembic commands ###