"""Add OTPToken support

Revision ID: a79000e54375
Revises: 20260310_sota_models
Create Date: 2026-03-11 14:08:13.780084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = 'a79000e54375'
down_revision: Union[str, None] = '20260310_sota_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###