"""Add token verification to TeacherProfile

Revision ID: b728bd168525
Revises: 96029914f94b
Create Date: 2026-03-17 09:12:15.739172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = 'b728bd168525'
down_revision: Union[str, None] = '96029914f94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacherprofile', sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('teacherprofile', sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_teacherprofile_invite_token'), 'teacherprofile', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacherprofile_invite_token'), table_name='teacherprofile')
    op.drop_column('teacherprofile', 'invite_expires_at')
    op.drop_column('teacherprofile', 'invite_token')
    # ### end Alembic commands ###