"""us_07_add_quality_flag

Revision ID: d9c7a4e79518
Revises: b728bd168525
Create Date: 2026-03-17 20:30:49.710971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added to support SQLModel specific types if needed


# revision identifiers, used by Alembic.
revision: str = 'd9c7a4e79518'
down_revision: Union[str, None] = 'b728bd168525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ARCHITECTURAL FIX: Inject server_default to prevent NotNullViolation on existing records.
    op.add_column('contribution', sa.Column('quality_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_contribution_quality_flag'), 'contribution', ['quality_flag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_quality_flag'), table_name='contribution')
    op.drop_column('contribution', 'quality_flag')
    # ### end Alembic commands ###